import Head from 'next/head'
import 'src/styles/globals.css'
import { useBgColor } from '../hooks/useBgColor';
import { useCounter } from '../hooks/useCounter';
import { useInputArray } from '../hooks/useInputArray';

export default function App({ Component, pageProps }) {
  const counter = useCounter();
  const inputArray = useInputArray();
  useBgColor();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...inputArray} />
    </>
  )
}