import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Links } from '../components/Links'
import { Center } from '../components/Center'
import { Headline } from '@/components/Headline'
import { Header } from '@/components/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main className={styles.main}>
        <Headline page='about'>
          {<code className={styles.code}>pages/about.js</code>}
        </Headline>
        <Center page='about' />
        <Links />
      </main>
    </>
  )
}
